CREATE TYPE statusTypes AS ENUM ('ACTIVE', 'INACTIVE');

CREATE TABLE employees (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    FirstName varchar(50) not null,
    MiddleInitial char(1),
    LastName varchar(50) not null,
    DateOfBirth date,
    DateOfEmployment date not null,
    Status statusTypes default 'ACTIVE' not null
);